analytics: {}
color:
  brandColors:
    - '#A8A088'
    - '#000000'
    - '#989080'
    - '#000000'
    - '#000000'
  brandStrength: 0.9375
  lightness: 0.3125
  rhythmicContrast: 1
  saturation: 0.0625
cta: {}
layout_spectrum: 0
name: www.sstitan.org
opengraph: {}
purpose: []
typography_spectrum: 0.56095
